"""Generate per-camera images for visually validating lens distortion."""
from pathlib import Path

import cv2
import numpy as np

from multical.camera_fisheye import CameraFisheye


def representative_indices(image_count, maximum=3):
  """Return deterministic, evenly distributed image indexes."""
  if image_count <= 0 or maximum <= 0:
    return []
  count = min(int(maximum), int(image_count))
  return sorted(set(
    int(round(value))
    for value in np.linspace(0, image_count - 1, count)
  ))


def _safe_name(value):
  text = str(value)
  return "".join(
    character if character.isalnum() or character in "-_." else "_"
    for character in text
  )


def _as_bgr(image):
  if image.ndim == 2:
    return cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
  if image.ndim == 3 and image.shape[2] == 4:
    return cv2.cvtColor(image, cv2.COLOR_BGRA2BGR)
  return image.copy()


def _label(image, text):
  output = _as_bgr(image)
  cv2.rectangle(output, (0, 0), (output.shape[1], 34), (0, 0, 0), -1)
  cv2.putText(
    output, text, (10, 24), cv2.FONT_HERSHEY_SIMPLEX,
    0.65, (255, 255, 255), 1, cv2.LINE_AA
  )
  return output


def _standard_maps(camera, alpha):
  size = tuple(int(value) for value in camera.image_size)
  intrinsic = np.asarray(camera.intrinsic, dtype=np.float64)
  distortion = np.asarray(camera.dist, dtype=np.float64)
  new_intrinsic, roi = cv2.getOptimalNewCameraMatrix(
    intrinsic, distortion, size, float(alpha), size
  )
  map_x, map_y = cv2.initUndistortRectifyMap(
    intrinsic, distortion, None, new_intrinsic, size, cv2.CV_32FC1
  )
  return new_intrinsic, tuple(int(value) for value in roi), map_x, map_y


def _fisheye_maps(camera, alpha):
  size = tuple(int(value) for value in camera.image_size)
  intrinsic = np.asarray(camera.intrinsic, dtype=np.float64)
  distortion = np.asarray(camera.dist, dtype=np.float64).reshape(-1, 1)
  new_intrinsic = cv2.fisheye.estimateNewCameraMatrixForUndistortRectify(
    intrinsic,
    distortion,
    size,
    np.eye(3),
    balance=float(alpha),
    new_size=size
  )
  map_x, map_y = cv2.fisheye.initUndistortRectifyMap(
    intrinsic,
    distortion,
    np.eye(3),
    new_intrinsic,
    size,
    cv2.CV_32FC1
  )
  return new_intrinsic, (0, 0, size[0], size[1]), map_x, map_y


def undistortion_maps(camera, alpha):
  if isinstance(camera, CameraFisheye):
    return _fisheye_maps(camera, alpha)
  return _standard_maps(camera, alpha)


def _write_image(filename, image):
  if not cv2.imwrite(
    str(filename), image, [int(cv2.IMWRITE_JPEG_QUALITY), 92]
  ):
    raise RuntimeError("could not write distortion check image {}".format(
      filename
    ))


def export_distortion_checks(
    output_path,
    camera_names,
    cameras,
    images,
    filenames,
    stage,
    max_images=3
):
  """Write original/undistorted comparison images.

  ``cameras`` must contain the final camera objects for the calibration stage.
  ``images`` and ``filenames`` are lists grouped by camera.
  """
  destination = Path(output_path) / "distortion_check"
  destination.mkdir(parents=True, exist_ok=True)
  legacy_manifest = destination / "manifest.json"
  if legacy_manifest.is_file():
    legacy_manifest.unlink()

  manifest = {
    "stage": str(stage),
    "convention": (
      "alpha=1 preserves more field of view; alpha=0 minimizes invalid "
      "borders. Images use the final intrinsics of this calibration run."
    ),
    "max_images_per_camera": int(max_images),
    "cameras": {}
  }

  for camera_name, camera, camera_images, camera_files in zip(
      camera_names, cameras, images, filenames
  ):
    camera_directory = destination / _safe_name(camera_name)
    camera_directory.mkdir(parents=True, exist_ok=True)
    # Remove files generated by an earlier run, including the legacy
    # standalone original/full/min-border images.
    for old_image in camera_directory.glob("view_*.jpg"):
      old_image.unlink()

    full_k, full_roi, full_map_x, full_map_y = undistortion_maps(
      camera, 1.0
    )
    crop_k, crop_roi, crop_map_x, crop_map_y = undistortion_maps(
      camera, 0.0
    )

    camera_manifest = {
      "model": str(camera.model),
      "fisheye": bool(isinstance(camera, CameraFisheye)),
      "image_size": [int(value) for value in camera.image_size],
      "K": np.asarray(camera.intrinsic, dtype=np.float64).tolist(),
      "dist": np.asarray(camera.dist, dtype=np.float64).tolist(),
      "full_view": {
        "alpha": 1.0,
        "new_K": full_k.tolist(),
        "roi": list(full_roi)
      },
      "minimal_border": {
        "alpha": 0.0,
        "new_K": crop_k.tolist(),
        "roi": list(crop_roi)
      },
      "views": []
    }

    for output_index, image_index in enumerate(
        representative_indices(len(camera_images), max_images), start=1
    ):
      original = camera_images[image_index]
      expected_size = tuple(int(value) for value in camera.image_size)
      actual_size = (int(original.shape[1]), int(original.shape[0]))
      if actual_size != expected_size:
        raise ValueError(
          "distortion check image size {} does not match {} calibration "
          "size {}".format(actual_size, camera_name, expected_size)
        )

      full = cv2.remap(
        original, full_map_x, full_map_y, cv2.INTER_CUBIC,
        borderMode=cv2.BORDER_CONSTANT
      )
      crop = cv2.remap(
        original, crop_map_x, crop_map_y, cv2.INTER_CUBIC,
        borderMode=cv2.BORDER_CONSTANT
      )

      prefix = "view_{:02d}".format(output_index)
      comparison_name = "{}_comparison.jpg".format(prefix)

      comparison = np.hstack([
        _label(original, "ORIGINAL"),
        _label(full, "UNDISTORTED alpha=1"),
        _label(crop, "UNDISTORTED alpha=0")
      ])
      _write_image(camera_directory / comparison_name, comparison)

      source_name = (
        str(camera_files[image_index])
        if image_index < len(camera_files) else None
      )
      camera_manifest["views"].append({
        "source_index": int(image_index),
        "source_image": source_name,
        "comparison": comparison_name
      })

    manifest["cameras"][str(camera_name)] = camera_manifest

  return manifest, destination
